### ISSUE TITLE
If server is deleted while controller is running it crashes

### ISSUE THREAD

**Issue by necrogami** [pobiega/bitburner-ts#1]
```
RUNTIME ERROR
controller.js@home

getServerUsedRam: Invalid hostname or IP: pserv-1

Stack:
controller.js:L110@calculateAvailableCycles
controller.js:L121@expFarm
controller.js:L340@async Module.main
```

I upgraded my server while my controller was running and it crashed the controller script.

**Comment by pobiega** [comment]
There is no good way to fix this, the controller checks what servers are available at the start of each cycle, and having to check if a server still exists every time before interacting with it would increase the already heavy CPU load by the controller.

I'll try to keep this in mind when designing the V2 version thou, which will be task based.
